### ISSUE TITLE
更加EMMC分区大小与增加分区 

### ISSUE THREAD

**Issue by gexindz** [OpenNuvoton/MA35D1_NuWriter#1]
怎么更改EMMC分区大小与增加分区，没有在Nuwirte找到相关的选项？

**Comment by ychuang3** [comment]
NuWriter 是直接寫入到 storage 指定的 physcial offset，不會看 partition 及文件系統
要分區的的話，應該是要先做好分區，再用 NuWriter 寫 image

**Comment by gexindz** [comment]
> NuWriter 是直接寫入到 storage 指定的 physcial offset，不會看 partition 及文件系統 要分區的的話，應該是要先做好分區，再用 NuWriter 寫 image

我觉得下载工具最好是可以对eMMC分区，然后下载，提高效率，我们之前用NXP I.MX的下载工具都是可以直接对eMMC分区。
