### ISSUE TITLE
USB烧录程序异常，无法正常Attach

### ISSUE THREAD

**Issue by zhuixinghuali** [OpenNuvoton/MA35D1_NuWriter#3]
SystemExit: No backend availableException ignored in: <function XUsbComList.__del__ at 0x00000214CBC49CA0>Traceback (most recent call last):
  File "xusbcom.py", line 189, in __del__
AttributeError: 'XUsbComList' object has no attribute 'devices'

![image](https://github.com/user-attachments/assets/3f4febbf-3979-4cb2-824c-598f097e87e4)
![image](https://github.com/user-attachments/assets/dd0e714f-918e-4e8d-a58a-921ab8135902)
![image](https://github.com/user-attachments/assets/81747aab-1cc2-4b0b-b77e-0708ba708220)

**Comment by zhuixinghuali** [comment]
尝试重启、重复点击Attach都不正常。技术让用工具(DeviceCleanup.exe)删除一些USB使用痕迹，管用，但是管不长。

**Comment by ychuang3** [comment]
需要安裝 python 模組，請閱讀 NuWriter User Manual  (UM_EN_MA35_NuWriter.pdf  在 root directory)

**Comment by zhuixinghuali** [comment]
python 模块已经安装了的。今天排查出问题了，受加密软件影响了。
